name: Audiobookshelf Server
version: 1.2.3
slug: audiobookshelfserver
description: Self-hosted audiobook & podcast server
arch:
  - amd64
  - aarch64
boot: manual
options:
  CONFIG_PATH: /config
  METADATA_PATH: /config/metadata
  BACKUP_PATH: /backup/audiobookshelfserver
  ALLOW_CORS: 0
  ALLOW_IFRAME: 1
  TZ: America/Los_Angeles
  ACCESS_TOKEN_EXPIRY: 43200
  REFRESH_TOKEN_EXPIRY: 604800
schema:
  CONFIG_PATH: str
  METADATA_PATH: str
  BACKUP_PATH: str
  ALLOW_CORS: int
  ALLOW_IFRAME: int
  TZ: str
  ACCESS_TOKEN_EXPIRY: int
  REFRESH_TOKEN_EXPIRY: int
ports:
  80/tcp: 13379
ports_description:
  13379/tcp: Web interface port
webui: http://[HOST]:[PORT:13379]
legacy: true
map:
  - media:rw
  - addon_config:rw
  - backup:rw
  - share:rw
panel_icon: book-music
panel_title: AudioBookShelf
